[[pages]]
path = "pages/íŒ€ ì´ì  ì˜ˆì¸¡.py"
name = "íŒ€ ì´ì  ì˜ˆì¸¡"
icon = "âš½"

[[pages]]
path = "pages/ê°€ìƒì„ ìˆ˜ ì´ì  ì˜ˆì¸¡.py"
name = "ê°€ìƒì„ ìˆ˜ ì´ì  ì˜ˆì¸¡"
icon = "ğŸ¯"

[[pages]]
path = "pages/ë°ì´í„° ì‹œê°í™”.py"
name = "ë°ì´í„° ì‹œê°í™”"
icon = "ğŸ“Š"
